WIKIPEDIA_XML_FILEPATH_TEST = 'backend/fixtures/test_wikipedia_snippet.xml'
WIKIPEDIA_XML_FILEPATH_FULL = '/data/wikipedia/enwiki-20150901-pages-articles-multistream.xml'
BATCH_ARTICLE_FILE = '/home/ubuntu/batch_article.csv'
BATCH_LINK_FILE = '/home/ubuntu/batch_link.csv'
NEO4J_USERNAME = 'neo4j'
NEO4J_PASSWORD = 'neo4j123'
NEO4J_SERVER = 'localhost'
NEO4J_PORT = 7474
SHORTEST_PATH_LIMIT=6
NODE_COUNT =162652