# -*- coding: utf-8 -*-

__author__ = 'Peter.Ogden'
__copyright__ = 'Copyright (C) 2015, Auto Trader UK'

mock_data = [{'pageid': 677947840,
              'name': 'Anarchism',
              'linkedArticles': ['anarcha-feminist', 'individual reclamation', 'Adolf Brand', 'Josiah Warren',
                                 '1917 October Revolution', 'market economy', 'direct action', 'will (philosophy)',
                                 'anarcha-feminism', 'idolatry', 'Anarchism in Mexico', 'Lysander Spooner',
                                 'Luc\xc3\xada S\xc3\xa1nchez Saornil', 'English Civil War', 'Libcom.org', 'Plato',
                                 'G8', 'Sebastien Faure', 'civilization', 'Nihilist movement', 'Anarchism and religion',
                                 'Ricardo Flores Mag\xc3\xb3n', 'imamate', 'Volin', 'anarchist communism',
                                 'Chicago Tribune', 'Edna St. Vincent Millay', 'Verso Books', 'Dwight Macdonald',
                                 'Synthesis anarchism', 'labour movement', 'egoist anarchism', 'Robert Owen',
                                 'BBC Radio 4', 'socialist', 'postcolonialism', 'Mother Earth (magazine)',
                                 'anti war movement', 'Category:Political culture', 'State (polity)',
                                 'security culture', 'Catalan people',
                                 'Encyclop\xc3\xa6dia Britannica Eleventh Edition',
                                 'Swedish Anarcho-syndicalist Youth Federation', 'Diogenes of Sinope', 'New Right',
                                 'Progressive education', 'Umberto I of Italy', 'File:Makhno group.jpg', 'Bolsheviks',
                                 'Anarchist schools of thought', 'NEFAC', 'Jacques Ellul', 'Spanish Communist Party',
                                 'AK Press', 'Crypto-anarchism', 'ruling class', 'Anarchist economics',
                                 'Gustave Courbet', 'Anti-fascism', 'Platformist', 'Left-wing market anarchism',
                                 'Confederaci\xc3\xb3n General del Trabajo', 'propaganda of the deed',
                                 'William B. Greene', 'Platformism', 'Federaci\xc3\xb3n Anarquista Ib\xc3\xa9rica',
                                 'Lists of anarchism topics', 'Fraye Arbeter Shtime', 'Adolf Hitler', 'oxymoron',
                                 'An Anarchist FAQ', 'Marie Fran\xc3\xa7ois Sadi Carnot', 'Paris Commune',
                                 'means of production', 'platformism', 'William Godwin', 'Oranienburg', 'Free Society',
                                 'Henry David Thoreau', 'synthesis anarchism', 'privative alpha', 'George I of Greece',
                                 'communards', 'Gustav Landauer', 'Lucifer the Lightbearer', 'Moses Harman',
                                 'Facing the Enemy', 'coercion', 'regicide', 'rationalist', 'simple living',
                                 'File:Kropotkin2.jpg', 'Resistance during World War II', 'Baja California',
                                 'Illegalism', 'individualism', 'markets', 'Crass', 'black bloc',
                                 'File:Paul Goodman.jpg', "International Workers' Day", 'Bilbao', 'Left-wing politics',
                                 'Empress Elisabeth of Austria', 'Free association (communism and anarchism)',
                                 'general strike', 'Online etymology dictionary', 'Margaret Anderson', 'veganarchism',
                                 'Traditional knowledge', 'Japanese Anarchist Federation', 'Pierre Monatte',
                                 'File:Portrait of Pierre Joseph Proudhon 1865.jpg', 'sovereign individual',
                                 'sexual revolution', 'affinity groups', 'Naturism', 'Coercion',
                                 'Bavarian Soviet Republic', 'abstentionism', 'Eugene Varlin', 'Marxist',
                                 'Renaissance humanism', 'Mexican Liberal Party',
                                 'List of films dealing with Anarchism', 'Friedrich Engels', 'Netherlands',
                                 'File:Jarach and Zerzan.JPG', 'Caliphate', 'Anarchism and Other Essays', 'Marxism',
                                 'Anarcho-pacifism', 'John Cage', 'Arthur Rimbaud', 'Umanita Nova', 'Joseph Goebbels',
                                 'anarchism and nationalism', 'Paul Goodman (writer)', 'Peter Kropotkin',
                                 'Anselme Bellegarrigue', 'Dielo Truda', '\xc3\x89tienne de La Bo\xc3\xa9tie',
                                 'moral obligation', 'hedonist', 'Free Territory (Ukraine)', '-ism', 'neo-liberalism',
                                 'Austrian School', 'Paul Avrich', 'philosophy', 'freethought', 'Conservatism',
                                 'anarchist economics', 'Cavalier', 'Maximilien de Robespierre', 'Comstockery',
                                 'lesbian', 'Anarchism in France', 'World Economic Forum',
                                 'Fernando Tarrida del M\xc3\xa1rmol', 'right libertarianism', 'Pierre Joseph Proudhon',
                                 "women's rights", 'Bob Black', 'Taoism', 'common ownership', 'Daniel Guerin',
                                 'Bohemianism', 'William Batchelder Greene', 'Collective farming', 'popular education',
                                 'Anarchist symbolism', 'File:Gadewar.jpg', 'Protestant Christianity',
                                 'state socialism', 'April Carter', 'Stephen Pearl Andrews', 'World Trade Organization',
                                 'anarchist schools of thought', 'Foundation for Economic Education', 'Pluto Press',
                                 'Libertarianism', 'Confederaci\xc3\xb3n Nacional del Trabajo', 'Levante, Spain',
                                 'Erich M\xc3\xbchsam', 'Wilhelm Weitling', 'Kharijites', 'Bolshevik',
                                 'libertarian socialism', 'Kegan Paul', 'Anarchist Aragon', 'anti-statism',
                                 'social democrats', 'Post-left anarchy', 'Age of Enlightenment', 'Blanquism',
                                 'WP:SEEALSO', 'Walden', 'mutual aid (organization)', 'List of anarchist communities',
                                 'anarchism and capitalism', 'privative', 'revolutions of 1848', 'Merriam-Webster',
                                 'punk rock', 'L. Susan Brown', 'Max Stirner',
                                 'Association of Private Enterprise Education', 'Jacobin (politics)', 'agriculture',
                                 'anarchy', 'Gay Liberation Front', 'reformism',
                                 'Image:Levellers declaration and standard.gif', 'hierarchical organisation',
                                 'polyamory', 'anarchist communists', 'International Anarchist Congress of Amsterdam',
                                 'The Ego and Its Own', 'Ukraine', 'Civil Disobedience (Thoreau)',
                                 'A Vindication of Natural Society', 'Spanish Civil War', 'David Graeber',
                                 'Anarchism and issues related to love and sex', 'James Guillaume',
                                 'Insurrectionary anarchism', 'Fernand Pelloutier',
                                 "International Workers' Association", 'individualist anarchism in France',
                                 'Routledge Encyclopedia of Philosophy', 'Bulgaria', 'Voline', 'Zeno of Citium',
                                 'anarcho-communists', 'Hierarchy', 'libertarianism', 'bisexuality',
                                 'Right-libertarianism', 'Category:Political ideologies', 'Henri Zisly',
                                 'Eight-hour day', 'Freetown Christiania', 'Dorothy Day', 'Mikhail Bakunin',
                                 'File:Members of the Maquis in La Tresorerie.jpg', 'Propagandaministerium',
                                 'Ezra Heywood', 'Johann Heinrich Pestalozzi', 'individual reappropriation',
                                 'Modern School (United States)', 'archon', 'socialist movement',
                                 'University of Westminster', 'Max Nettlau', 'Political Justice',
                                 'Category:Far-left politics', 'George Woodcock', 'Reichstag fire', 'Anti-Christianity',
                                 'decentralised', 'deschooling', 'Christian movement', 'squatter',
                                 'Anarchism in Germany', 'Catalonia', 'Louise Michel', 'W. W. Norton &amp; Company',
                                 'European individualist anarchism', 'Outline of anarchism', 'Pierre-Joseph Proudhon',
                                 'Thomas Hodgskin', 'Mexican Revolution', 'wikt:anarchism', 'Blackshirts',
                                 'Russian Civil War', 'property rights', 'anti-authoritarian', 'propaganda by the deed',
                                 'from each according to his ability, to each according to his need',
                                 'Feminist movement', 'Confiscation', 'The New Humanist', 'individual',
                                 'Popular education', 'Anarchism in Russia', 'Uruguayan Anarchist Federation',
                                 'Anarcha-feminism', 'Conf\xc3\xa9d\xc3\xa9ration g\xc3\xa9n\xc3\xa9rale du travail',
                                 'Cynicism (philosophy)', "workers' council", 'The Word (free love)',
                                 'Charles W. Johnson (philosopher)', 'Allen Ginsberg', 'Bucknell University Press',
                                 'Campaign for Nuclear Disarmament', 'insurrection',
                                 'List of anarchist movements by region', "Workers' self-management", 'self-governance',
                                 'free market', 'Ruth Kinna', 'Solidarity Federation', 'Carlos I of Portugal',
                                 'February Revolution', 'definitional concerns in anarchist theory', 'heterosexual',
                                 'Sex Pistols', 'German Revolution of 1918\xe2\x80\x931919',
                                 'Mexican Anarchist Federation', 'Anarchism and Marxism', 'October Revolution',
                                 'Luigi Galleani', 'Universit\xc3\xa0 popolare (Italian newspaper)', 'Stuart Christie',
                                 'Anti-nuclear movement', 'H\xc3\xa9bertists', 'private property', 'Luigi Fabbri',
                                 'morality', 'Communist party', 'Sam Dolgoff', 'stirner', 'Arditi del Popolo',
                                 'Benedict Anderson', 'Daniel Gu\xc3\xa9rin', 'Ammon Hennacy', 'social ecology',
                                 'commune (intentional community)', 'Oscar Wilde', 'Nazism', 'French Revolution',
                                 'File:Lugi Gallean2.jpg', 'Francesc Ferrer i Gu\xc3\xa0rdia', 'post-left anarchy',
                                 'Park G\xc3\xbcell', 'Levellers', 'Comintern', 'Encyclopedia Britannica',
                                 'The Globe and Mail', 'anarchism without adjectives', 'social control', 'illegalism',
                                 'Michel Onfray', 'Muslim', 'Max Baginski',
                                 'Central Organisation of the Workers of Sweden', 'syndicalism',
                                 'Federaci\xc3\xb3n Obrera Regional Argentina', 'Anarchism in Spain',
                                 'Iberian Anarchist Federation', 'Issues in anarchism',
                                 'International of Anarchist Federations', 'Emma Goldman', 'Reign of Terror',
                                 'anarchist free school', "International Workingmen's Association", 'Albert Meltzer',
                                 'Cantonal Revolution', 'Oxford University Press', 'Karl Marx',
                                 'S\xc3\xa9bastien Faure', 'left-wing', 'humanism', 'non-violence', 'Carrara',
                                 'political philosophy', 'Elis\xc3\xa9e Reclus', 'ZNet', 'Kevin Carson',
                                 'libertarian socialist', 'Freethought', 'Routledge', 'Russian Revolution (1917)',
                                 'Emile Armand', 'insurrectionary anarchism', 'Francisco Franco', 'Growing Up Absurd',
                                 'social anarchism', 'Revolutions of 1917\xe2\x80\x9323', 'Zhuang Zhou',
                                 'Free Territory', 'White movement', 'Greenwich Village', 'Virginia Bolten',
                                 'transcendentalist', 'public choice theory', 'wikt:brigand', 'Red Army Faction',
                                 'Alexander Berkman', 'free love', 'Nestor Makhno', 'Mutualism (economic theory)',
                                 'Anarchist Federation (Britain and Ireland)', 'Anarchist St. Imier International',
                                 'censorship', 'File:Manifestaci\xc3\xb3n CNT Bilbao.jpg', 'Diggers',
                                 'Communist Party of Germany', 'Tolstoy', 'LGBT', 'biennio rosso', 'anti-clerical',
                                 'League of Peace and Freedom', 'Stalinist purges',
                                 'Anarchism: A Documentary History of Libertarian Ideas', 'anti-capitalist',
                                 'minarchism', 'Category:Social theories', 'James C. Scott', 'First International',
                                 'homosexuality', 'Squatting', 'Revolutionary Insurrectionary Army of Ukraine',
                                 'spontaneous order', 'Oranienburg concentration camp', 'anarcho-communism',
                                 'negative liberty', 'post-modernism', 'Anarchism in Italy', 'Leopold Kohr',
                                 'union of egoists', 'lois sc\xc3\xa9l\xc3\xa9rates', 'counterculture',
                                 'Miguel Gimenez Igualada', 'philosophical anarchism', 'In Our Time (BBC Radio 4)',
                                 'International Libertarian Solidarity', 'Ivan Illich', 'Counterculture of the 1960s',
                                 'strikebreaker', "Workers' Party of Marxist Unification", 'Stoicism',
                                 'Beno\xc3\xaet Broutchoux', 'F\xc3\xa9d\xc3\xa9ration Anarchiste',
                                 'political theology', 'patriarchy', 'anarchist law', 'Melvyn Bragg',
                                 'File:WilliamGodwin.jpg', 'Summerhill School', 'positive liberty', 'Sonnenburg',
                                 'Renzo Novatore', 'Direct action', 'File:Fransisco Ferrer Guardia.jpg',
                                 'stateless society', 'Nazi concentration camps', 'History of Germany since 1945',
                                 'collectivization', 'Synthesist anarchism', 'Libertarian Alliance', 'Adolphe Thiers',
                                 'Han Ryner', 'birth control', 'Federation of Organized Trades and Labor Unions',
                                 'Communist Party of Spain (main)', 'technology', 'Workers Solidarity Movement',
                                 'Edmund Burke', 'state (polity)', 'Herbert Read', 'left libertarianism', 'utilitarian',
                                 'far right leagues', 'Limited government', 'Pejorative', 'Clifford Harper',
                                 'The Oxford Companion to Philosophy', 'Murray Bookchin',
                                 'Industrial Workers of the World', 'Alexandre Skirda', 'Hague Congress (1872)',
                                 'Stalinism', 'Saul Newman', 'Wikipedia:External links',
                                 'Reciprocity (cultural anthropology)', 'Category:Anarchism', 'individualist anarchist',
                                 'Political repression', 'Barcelona', 'The False Principle of our Education',
                                 'Enrag\xc3\xa9s', 'individualist anarchism', 'Now and After', 'Haymarket affair',
                                 'Soviet Union', 'File:ChicagoAnarchists.jpg', 'counter-economics', 'Rudolf Rocker',
                                 'Anarchism and capitalism', 'Geoffrey Ostergaard', 'The New York Times', 'Parma',
                                 'Black Rose Books', 'Simon Critchley', 'Abu Hanifa', 'Slate.com', 'united front',
                                 'Development criticism', 'John Henry Mackay', 'libcom.org', 'Collectivist anarchism',
                                 'File:ParcGuellOkupas.jpg', 'William Everard (Digger)', 'Laozi', 'feminist',
                                 'Loughborough University', 'Christiaan Cornelissen', "Syndicalist Workers' Federation",
                                 'anarcho-syndicalism', 'Andalusia', 'The Tyranny of Structurelessness', 'feminism',
                                 'trade union', 'autonomist marxism', 'Benjamin Tucker',
                                 'dictatorship of the proletariat', 'Mujeres Libres', 'File:Emilearmand01.jpg',
                                 'Voltairine de Cleyre', 'Post-anarchism', 'participatory economics',
                                 'Syncretic politics', 'direct democracy', 'Jean-Jacques Rousseau', 'Hakim Bey',
                                 'Green anarchism', 'Surrealism', 'labour unions', 'A. S. Neill', 'Spanish Revolution',
                                 'Bonnot Gang', 'Category:Anti-capitalism', 'Anarchism in Brazil',
                                 'Stonewall Rebellion', 'Amparo Poch y Gasc\xc3\xb3n', '6 February 1934 crisis',
                                 'enlightened self-interest', 'authority', 'class conflict', 'waqf',
                                 'Reification (fallacy)', 'libertarian anarchism', 'File:Max stirner.jpg',
                                 'Gerrard Winstanley', 'Francoism', 'anarcho-pacifist', 'Murray Rothbard', 'utopian',
                                 'Andrej Grubacic', 'My Disillusionment in Russia', 'Wikipedia:Spam',
                                 'christian anarchist', 'penal colonies', 'Libertarian socialism', 'federalist',
                                 'Camillo Berneri', 'Christian anarchism', 'mutually exclusive',
                                 'Lucifer, the Light-Bearer', 'The Kingdom of God is Within You',
                                 'Napoleon III of France', 'unschooling', 'Leo Tolstoy', 'M. E. Lazarus',
                                 'Spanish Anarchists', 'ideology', 'William McKinley', 'anarcho-primitivism',
                                 'Francesc Pi i Margall', 'What is Property?', 'International Workers Association',
                                 'Anarcho-capitalism', 'Lois Waisbrooker', 'wikt:Solidarity', 'File:Bakunin.png',
                                 'New Left Review', 'social revolution', 'Unione Sindacale Italiana', 'Lev Chernyi',
                                 'Alex Comfort', 'Pissarro', 'Leon Czolgosz', 'Encarta', 'collectivist anarchism',
                                 'Argentine Libertarian Federation', 'Nudism', '1848 Revolution',
                                 'Liberty (1881\xe2\x80\x931908)', 'Workers Solidarity Alliance', 'antimilitarism',
                                 'Anti-clericalism', 'infinitive', 'affinity group',
                                 'World Trade Organization Ministerial Conference of 1999 protest activity',
                                 'class struggle', 'nonviolence', 'John Zerzan', 'poststructuralist', 'Second Fitna',
                                 'Ronald Hamowy', 'Julian Beck', 'Category:Anti-fascism', 'Philadelphes',
                                 'Anarchy: A Journal of Desire Armed', 'centralism', 'Joseph D\xc3\xa9jacque',
                                 'Kronstadt rebellion', 'Cold War', 'Errico Malatesta', 'Silvio Gesell', 'tyrannicide',
                                 'voluntary association', 'anti-globalisation movement', 'New York Times',
                                 'Robespierre', 'F\xc3\xa9d\xc3\xa9ration anarchiste', 'anarcho-naturism',
                                 'personal property', 'Roundhead', 'Harold Barclay', 'The Joy of Sex',
                                 'Council communism', 'Johann Most', 'Bayerischer Rundfunk', 'toleration',
                                 'anarchism and religion', 'Anarchist Catalonia', 'Albert Camus', 'Protests of 1968',
                                 'Alexander II of Russia', 'Peter Marshall (author)', "Spain's economy",
                                 'Federazione Anarchica Italiana', 'Andr\xc3\xa9 Breton', 'Cuba',
                                 'Conf\xc3\xa9d\xc3\xa9ration nationale du travail', 'Property is theft',
                                 'Situationist International', 'law and economics']},
             {'pageid': 674604893,
              'name': 'Autism',
              'linkedArticles': ['Diagnostic and Statistical Manual of Mental Disorders', 'social cognition',
                                 'speech and language therapy', 'Sociological and cultural aspects of autism',
                                 'social stigma', 'DSM-5', 'echolalia', 'microglia', 'Remission (medicine)',
                                 'Category:Neurological disorders in children', 'gastrointestinal', 'Down syndrome',
                                 'cytokines', 'neurexin', 'chromosome abnormality', 'tuberous sclerosis',
                                 'Sensitivity (tests)', 'occupational therapy', 'Tourette syndrome', 'toe walking',
                                 'functional neuroimaging', 'neuropsychological', 'Mendelian', 'J Autism Dev Disord',
                                 'child care', 'high-functioning autism',
                                 'Alternative therapies for developmental and learning disabilities',
                                 'autism spectrum disorder', 'inflammation', 'diesel exhaust', 'epilepsy',
                                 'Vienna General Hospital', 'applied behavior analysis', 'Heritability of autism',
                                 'Idiosyncrasy', 'Deletion (genetics)', 'gestation', 'medical conditions', 'PDD-NOS',
                                 'Autism Diagnostic Interview-Revised', 'empathizing\xe2\x80\x93systemizing theory',
                                 'Peter Szatmari', 'Protein synthesis', 'Neuropsychol Rev', 'Hans Asperger',
                                 'neuroligin', 'primary care physician', 'Genotype-first approach', 'synapse',
                                 'Trends Neurosci', 'cognitive', 'Pronoun reversal', 'turn-taking',
                                 'language acquisition', 'Diagnosis of Asperger syndrome', 'Neurodiversity',
                                 'Clinical genetics', 'Trait (biology)', 'malnutrition', 'Autism Cymru',
                                 'intellectual disability', 'neurodevelopmental disorder', 'perceptual', 'fragile X',
                                 'Category:Neurological disorders', 'Spectrum disorder',
                                 'Early intensive behavioral intervention', 'executive functions',
                                 'Category:Pervasive developmental disorders', 'regressive autism', 'WP:MEDMOS',
                                 'Major depressive disorder', 'babbling', 'rubella', 'refrigerator mother',
                                 'Human brain', 'prognosis', 'schizophrenia', 'neurology', 'Sensory system',
                                 'Cell adhesion', 'specific language impairment', 'Metabolic', 'growth hormone',
                                 'Category:Mental and behavioural disorders', 'psychosocial',
                                 'Conditions comorbid to autism spectrum disorders', 'copy number variation',
                                 'Childhood Autism Rating Scale', 'blindism', 'Attachment in children', 'BMJ',
                                 'Hyperbaric medicine', 'review', 'nerve cell', 'IQ', 'stress (psychological)',
                                 'mutation', 'File:US-autism-6-17-1996-2007.png', 'child psychology',
                                 'infectious disease', 'gene expression', 'diffusion tensor imaging', 'Gesture',
                                 'phenylketonuria', 'epigenetic', 'solvent', 'dendritic spine', 'Gene duplication',
                                 'fusiform face area', 'phthalates', 'heavy metal (chemistry)',
                                 'An Anthropologist on Mars', 'Johns Hopkins Hospital', 'language disorder',
                                 'neural development', 'Joint attention', 'prenatal stress', 'language development',
                                 'Table Talk (Luther)', 'Environmental factor', 'vaccine', 'antipsychotic',
                                 'File:Powell2004Fig1A.jpeg', 'tantrum', 'neuropsychologist', 'Category:Autism', 'PCBs',
                                 'Regressive autism', 'social norms', 'Weak central coherence theory',
                                 'Thiomersal controversy', 'Specificity (tests)', 'Leo Kanner',
                                 'Landau\xe2\x80\x93Kleffner syndrome', 'Autism Diagnostic Observation Schedule',
                                 'Minor physical anomalies', 'brominated flame retardant',
                                 'File:Autistic-sweetiepie-boy-with-ducksinarow.jpg', 'neurogenetic',
                                 'executive dysfunction', 'File:Single Chromosome Mutations.svg', 'casein-free diet',
                                 'dysmorphic feature', 'pervasive developmental disorder', 'Nature Reviews Genetics',
                                 'feral child', 'fragile X syndrome', 'WP:MEDRS', 'Syndrome',
                                 'metabotropic glutamate receptors', 'Asperger syndrome', 'Screening (medicine)',
                                 'Intellectual disability', 'brain scan', "Parkinson's", 'New Latin',
                                 'social communication', 'Controversies in autism', 'pregnancy',
                                 'developmentally disabled', 'Rett syndrome', 'magnetoencephalography', 'Teratology',
                                 'MMR vaccine controversy', 'Dermatillomania', 'antidepressant', 'neurochemical',
                                 'Anxiety disorder', 'Medical diagnosis', 'Savant syndrome',
                                 'Attention deficit hyperactivity disorder', 'Adverse effect (medicine)',
                                 'File:Autismbrain.jpg', 'Eugen Bleuler', 'Int J Dev Neurosci', 'aripiprazole',
                                 'developmental milestones', 'Causes of autism', '1q21.1 deletion syndrome',
                                 'PDD not otherwise specified', 'Synapse', 'Genetic disorder', 'DNA', 'efficacy',
                                 'pesticide', 'Ritual', 'teratogen', 'special education', 'serotonin', 'eye contact',
                                 'Wild Boy of Aveyron', 'File:Opening a window to the autistic brain.jpg', 'Psychiatry',
                                 'metabolic defect', 'visually impaired', 'National Health Service',
                                 'genetic screening', 'cerebellum', 'Can J Neurol Sci', 'birth defect', 'insomnia',
                                 'phenols', 'Electroencephalography', 'neuronal migration', 'Cerebral hemisphere',
                                 'Human embryogenesis', 'Human fertilization', 'pediatrician', 'medical specialist',
                                 'teratogens', 'medical care', 'mirror neuron system', 'social support',
                                 'rubella vaccine', 'non-verbal communication', 'File:Leo-Kanner.jpeg',
                                 'Vaccine controversy', 'Neuroanatomical', 'theory of mind', 'Apraxia',
                                 'Pediatr Clin North Am', 'neuron', 'psychoactive drug', 'Compulsive behavior',
                                 'Association areas', 'poor muscle tone', 'Category:Communication disorders',
                                 'Inhibition Theory', 'splinter skill', 'immune system', 'Self-injury',
                                 'childhood disintegrative disorder', 'Cerebral cortex', 'independent living',
                                 'task-positive network', 'Environ Health Perspect', 'Category:Psychiatric diagnosis',
                                 'pediatrics', 'self-referential', 'working memory', 'Martin Luther', 'autism spectrum',
                                 'Jean Marc Gaspard Itard', 'frontal lobe', 'Self-determination theory',
                                 'Clin Infect Dis', 'John Wiley &amp; Sons', 'estate planning', 'phenotype', 'Ethanol',
                                 'anticonvulsant', 'cell adhesion', 'nervous system', 'behavior therapy', 'stimulant',
                                 'event-related potential', 'fMRI', 'pedantic', 'risperidone', 'Face perception',
                                 'ICD-10', 'hearing impairment', 'default network', 'social skills', 'neuroimaging',
                                 'Quality of life', 'TEACCH', 'Cell (journal)', 'Sally\xe2\x80\x93Anne test', 'meiosis',
                                 'Swiss', 'growth factor receptor', 'Epilepsy', 'net present value', 'psychology',
                                 'Neurosci Biobehav Rev', 'pathophysiology', 'heritability', 'air pollution',
                                 'Oliver Sacks', 'Simon Baron-Cohen', 'inborn errors of metabolism',
                                 'differential diagnosis', 'neurotypical', 'illicit drug', 'Attachment (psychology)',
                                 'Autism rights movement', 'Temple Grandin', 'chelation therapy', 'psychiatry',
                                 'systematic review', 'Stereotypy', 'childhood immunizations',
                                 'Interpersonal relationship', 'middle-of-the-night insomnia']},
             {'pageid': 674604893,
              'name': 'Autism',
              'linkedArticles': ['Diagnostic and Statistical Manual of Mental Disorders', 'social cognition',
                                 'speech and language therapy', 'Sociological and cultural aspects of autism',
                                 'social stigma', 'DSM-5', 'echolalia', 'microglia', 'Remission (medicine)',
                                 'Category:Neurological disorders in children', 'gastrointestinal', 'Down syndrome',
                                 'cytokines', 'neurexin', 'chromosome abnormality', 'tuberous sclerosis',
                                 'Sensitivity (tests)', 'occupational therapy', 'Tourette syndrome', 'toe walking',
                                 'functional neuroimaging', 'neuropsychological', 'Mendelian', 'J Autism Dev Disord',
                                 'child care', 'high-functioning autism',
                                 'Alternative therapies for developmental and learning disabilities',
                                 'autism spectrum disorder', 'inflammation', 'diesel exhaust', 'epilepsy',
                                 'Vienna General Hospital', 'applied behavior analysis', 'Heritability of autism',
                                 'Idiosyncrasy', 'Deletion (genetics)', 'gestation', 'medical conditions', 'PDD-NOS',
                                 'Autism Diagnostic Interview-Revised', 'empathizing\xe2\x80\x93systemizing theory',
                                 'Peter Szatmari', 'Protein synthesis', 'Neuropsychol Rev', 'Hans Asperger',
                                 'neuroligin', 'primary care physician', 'Genotype-first approach', 'synapse',
                                 'Trends Neurosci', 'cognitive', 'Pronoun reversal', 'turn-taking',
                                 'language acquisition', 'Diagnosis of Asperger syndrome', 'Neurodiversity',
                                 'Clinical genetics', 'Trait (biology)', 'malnutrition', 'Autism Cymru',
                                 'intellectual disability', 'neurodevelopmental disorder', 'perceptual', 'fragile X',
                                 'Category:Neurological disorders', 'Spectrum disorder',
                                 'Early intensive behavioral intervention', 'executive functions',
                                 'Category:Pervasive developmental disorders', 'regressive autism', 'WP:MEDMOS',
                                 'Major depressive disorder', 'babbling', 'rubella', 'refrigerator mother',
                                 'Human brain', 'prognosis', 'schizophrenia', 'neurology', 'Sensory system',
                                 'Cell adhesion', 'specific language impairment', 'Metabolic', 'growth hormone',
                                 'Category:Mental and behavioural disorders', 'psychosocial',
                                 'Conditions comorbid to autism spectrum disorders', 'copy number variation',
                                 'Childhood Autism Rating Scale', 'blindism', 'Attachment in children', 'BMJ',
                                 'Hyperbaric medicine', 'review', 'nerve cell', 'IQ', 'stress (psychological)',
                                 'mutation', 'File:US-autism-6-17-1996-2007.png', 'child psychology',
                                 'infectious disease', 'gene expression', 'diffusion tensor imaging', 'Gesture',
                                 'phenylketonuria', 'epigenetic', 'solvent', 'dendritic spine', 'Gene duplication',
                                 'fusiform face area', 'phthalates', 'heavy metal (chemistry)',
                                 'An Anthropologist on Mars', 'Johns Hopkins Hospital', 'language disorder',
                                 'neural development', 'Joint attention', 'prenatal stress', 'language development',
                                 'Table Talk (Luther)', 'Environmental factor', 'vaccine', 'antipsychotic',
                                 'File:Powell2004Fig1A.jpeg', 'tantrum', 'neuropsychologist', 'Category:Autism', 'PCBs',
                                 'Regressive autism', 'social norms', 'Weak central coherence theory',
                                 'Thiomersal controversy', 'Specificity (tests)', 'Leo Kanner',
                                 'Landau\xe2\x80\x93Kleffner syndrome', 'Autism Diagnostic Observation Schedule',
                                 'Minor physical anomalies', 'brominated flame retardant',
                                 'File:Autistic-sweetiepie-boy-with-ducksinarow.jpg', 'neurogenetic',
                                 'executive dysfunction', 'File:Single Chromosome Mutations.svg', 'casein-free diet',
                                 'dysmorphic feature', 'pervasive developmental disorder', 'Nature Reviews Genetics',
                                 'feral child', 'fragile X syndrome', 'WP:MEDRS', 'Syndrome',
                                 'metabotropic glutamate receptors', 'Asperger syndrome', 'Screening (medicine)',
                                 'Intellectual disability', 'brain scan', "Parkinson's", 'New Latin',
                                 'social communication', 'Controversies in autism', 'pregnancy',
                                 'developmentally disabled', 'Rett syndrome', 'magnetoencephalography', 'Teratology',
                                 'MMR vaccine controversy', 'Dermatillomania', 'antidepressant', 'neurochemical',
                                 'Anxiety disorder', 'Medical diagnosis', 'Savant syndrome',
                                 'Attention deficit hyperactivity disorder', 'Adverse effect (medicine)',
                                 'File:Autismbrain.jpg', 'Eugen Bleuler', 'Int J Dev Neurosci', 'aripiprazole',
                                 'developmental milestones', 'Causes of autism', '1q21.1 deletion syndrome',
                                 'PDD not otherwise specified', 'Synapse', 'Genetic disorder', 'DNA', 'efficacy',
                                 'pesticide', 'Ritual', 'teratogen', 'special education', 'serotonin', 'eye contact',
                                 'Wild Boy of Aveyron', 'File:Opening a window to the autistic brain.jpg', 'Psychiatry',
                                 'metabolic defect', 'visually impaired', 'National Health Service',
                                 'genetic screening', 'cerebellum', 'Can J Neurol Sci', 'birth defect', 'insomnia',
                                 'phenols', 'Electroencephalography', 'neuronal migration', 'Cerebral hemisphere',
                                 'Human embryogenesis', 'Human fertilization', 'pediatrician', 'medical specialist',
                                 'teratogens', 'medical care', 'mirror neuron system', 'social support',
                                 'rubella vaccine', 'non-verbal communication', 'File:Leo-Kanner.jpeg',
                                 'Vaccine controversy', 'Neuroanatomical', 'theory of mind', 'Apraxia',
                                 'Pediatr Clin North Am', 'neuron', 'psychoactive drug', 'Compulsive behavior',
                                 'Association areas', 'poor muscle tone', 'Category:Communication disorders',
                                 'Inhibition Theory', 'splinter skill', 'immune system', 'Self-injury',
                                 'childhood disintegrative disorder', 'Cerebral cortex', 'independent living',
                                 'task-positive network', 'Environ Health Perspect', 'Category:Psychiatric diagnosis',
                                 'pediatrics', 'self-referential', 'working memory', 'Martin Luther', 'autism spectrum',
                                 'Jean Marc Gaspard Itard', 'frontal lobe', 'Self-determination theory',
                                 'Clin Infect Dis', 'John Wiley &amp; Sons', 'estate planning', 'phenotype', 'Ethanol',
                                 'anticonvulsant', 'cell adhesion', 'nervous system', 'behavior therapy', 'stimulant',
                                 'event-related potential', 'fMRI', 'pedantic', 'risperidone', 'Face perception',
                                 'ICD-10', 'hearing impairment', 'default network', 'social skills', 'neuroimaging',
                                 'Quality of life', 'TEACCH', 'Cell (journal)', 'Sally\xe2\x80\x93Anne test', 'meiosis',
                                 'Swiss', 'growth factor receptor', 'Epilepsy', 'net present value', 'psychology',
                                 'Neurosci Biobehav Rev', 'pathophysiology', 'heritability', 'air pollution',
                                 'Oliver Sacks', 'Simon Baron-Cohen', 'inborn errors of metabolism',
                                 'differential diagnosis', 'neurotypical', 'illicit drug', 'Attachment (psychology)',
                                 'Autism rights movement', 'Temple Grandin', 'chelation therapy', 'psychiatry',
                                 'systematic review', 'Stereotypy', 'childhood immunizations',
                                 'Interpersonal relationship', 'middle-of-the-night insomnia']},
             {'pageid': 670440233,
              'name': 'Albedo',
              'linkedArticles': ['feedback', 'photovoltaic system', 'Category:Electromagnetic radiation',
                                 'File:Ceres 2003 2004 clear sky total sky albedo.png', 'solar zenith angle', 'Moon',
                                 'geometric albedo', 'comet nucleus', 'evapotranspiration', 'Polar see-saw', 'MODIS',
                                 'Johann Heinrich Lambert', 'Hadley Centre', 'visible light', 'carbon sequestration',
                                 'bidirectional reflectance distribution function', 'Category:Radiometry',
                                 'organic compound', 'contrail', 'electrical energy', 'Daisyworld',
                                 'cloud condensation nuclei', 'Sahara Desert', 'Emissivity', 'Irradiance',
                                 'specular reflection', 'angle of incidence', 'WP:SEEALSO', 'jet stream',
                                 'Category:Climate forcing', 'visible spectrum', 'Coriolis effect', 'positive feedback',
                                 'National Geographic (magazine)', 'black body', 'Tropical', 'frequency',
                                 'black carbon', 'Directional-hemispherical reflectance', 'Latin',
                                 'Solar radiation management',
                                 'Category:Scattering, absorption and radiative transfer (optics)',
                                 'bi-hemispherical reflectance', 'air mass', 'diffuse reflection', 'Bond albedo',
                                 'Aqua (satellite)', 'Category:Climatology', 'climate', 'pressure systems',
                                 'greenhouse effect', 'directional-hemispherical reflectance', 'Terra (satellite)',
                                 'NASA', 'Natural satellite', 'Dimensionless number', 'Earth observation',
                                 'refractive index', 'Solar System', 'Absolute magnitude',
                                 'Geophysical Research Letters', 'weather', 'Enceladus', 'photometry (astronomy)',
                                 'antarctic', 'insolation', 'File:Albedo-e hg.svg', 'Lambertian reflectance',
                                 'Diffuse reflection', 'Category:Radiation', 'reflectivity', 'asteroid',
                                 'Eris (dwarf planet)', 'air masses', 'Aerosols', 'sub-tropical', 'season',
                                 'opposition effect', 'rain forest', 'asteroid belt',
                                 'Leadership in Energy and Environmental Design', 'space weathering',
                                 'File:water reflectivity.jpg', 'planet', 'climatology', 'photosynthesis',
                                 'Hapke parameters', 'Intergovernmental Panel on Climate Change',
                                 'Single-scattering albedo', 'Deciduous trees', 'temperate forest', 'waviness',
                                 'terminator (solar)', 'Global dimming', 'coniferous trees', 'Cool roof', 'arctic',
                                 'deforestation', 'mathematical model', 'dust', 'Cryoconite', 'astronomy',
                                 'phase angle (astronomy)', 'Photometria', 'regolith', 'Fresnel equations',
                                 'Antarctica', 'Cloud albedo', 'Earth']},
             {'pageid': 160875429,
              'name': 'AutoRacing',
              'linkedArticles': ['Category:Russian essayists', 'Category:American writers of Russian descent',
                                 'Nabokov house', 'Universal Studios', 'Plato',
                                 'Objectivism: The Philosophy of Ayn Rand', 'anti-communist', 'Valhalla, New York',
                                 'Category:Jewish American novelists', 'University of Pittsburgh', 'Nicholas II', 'GQ',
                                 'Mother Jones (magazine)', 'The Fountainhead (film)', 'individual rights',
                                 'Kay Nolte Smith', 'Jiji Press', 'Category:American essayists', 'dictatorship',
                                 'Reason (magazine)', 'Nathaniel Branden', 'Friedrich Hayek', 'United States Congress',
                                 'Romance novel', "St. Martin's Press", 'neo-Romanticism', 'Leonard Peikoff',
                                 'William F. Buckley, Jr.', 'Category:American classical liberals', 'Aino (given name)',
                                 'John Chamberlain (journalist)', 'Yom Kippur War', 'The New York Times Book Review',
                                 'Objectivist movement', 'Tea Party protests', 'systematic philosophy',
                                 'Objectivism (Ayn Rand)', 'Rutland Herald', 'For the New Intellectual', 'magnum opus',
                                 'Category:American science fiction writers', 'House Un-American Activities Committee',
                                 'cult', 'Soviet Russia', 'anarchism', 'Vladimir Lenin', 'Jews',
                                 'Category:20th-century American dramatists and playwrights', 'Epcot',
                                 'Saint Petersburg State University', 'Reagan administration',
                                 'File:Ayn Rand quote, American Adventure, Epcot Center, Walt Disney World.jpg.jpg',
                                 'Category:American women novelists', 'Category:People of the New Deal arts projects',
                                 'Category:Jewish atheists', 'Kensico Cemetery', 'comic book',
                                 'Category:20th-century women writers', 'We the Living (film)', 'Rose Wilder Lane',
                                 'draft dodgers', 'axiom', 'Barry Goldwater', 'Friedrich Nietzsche',
                                 'democratic socialism', 'Chris Matthew Sciabarra', 'social pedagogy',
                                 'Ayn Rand Institute', 'Category:Writers from Saint Petersburg', 'romanticism',
                                 'American Writers Association', 'libertarian', 'Ford Hall Forum', 'E.E. Clive',
                                 'Category:Soviet emigrants to the United States', 'Left Behind', 'National Review',
                                 'free will', 'Category:Cardiovascular disease deaths in New York',
                                 'Category:Imperial Russian atheists', 'Category:Epistemologists', 'Austrian School',
                                 'Bobbs-Merrill Company', 'fascism', 'The New Left: The Anti-Industrial Revolution',
                                 'Michael Huemer', 'ethics', 'List of people on stamps of the United States',
                                 'capitalism', 'David Nolan (libertarian)', 'Alexander Kerensky', 'Hebrew',
                                 'Postage stamps and postal history of the United States',
                                 'Category:Jewish women writers', 'Nick Gaetano', 'Altruism (ethics)', 'Cyrillic',
                                 'classical liberalism', 'Permanent residence (United States)', 'Ira Levin',
                                 'Pola Negri', 'Book-of-the-Month Club', 'MIT',
                                 'Category:Russian dramatists and playwrights', 'strike action',
                                 'Radicals for Capitalism: A Freewheeling History of the Modern American Libertarian Movement',
                                 'Category:American people of Russian-Jewish descent', 'Philosophy',
                                 'Category:Objectivists', 'Category:Women essayists', 'John Galt',
                                 'Category:American anti-communists', 'The Night of January 16th (film)',
                                 'Category:American women screenwriters', 'Category:American political theorists',
                                 'libertarian movement', 'Category:1982 deaths', 'Bolshevik',
                                 'The Passion of Ayn Rand (book)', 'The Ayn Rand Lexicon',
                                 'Category:American women philosophers', 'Allan Gotthelf',
                                 'Category:American women dramatists and playwrights', 'File:TDTP08.JPG',
                                 'Category:Russian anti-communists', 'Category:Russian screenwriters', 'Garry Wills',
                                 'heart failure', 'Henry Hazlitt', 'Cato Unbound', 'Tara Smith (philosopher)',
                                 'Category:20th-century philosophers', 'Category:Russian women writers',
                                 'Category:Saint Petersburg State University alumni', 'The Journal of Ayn Rand Studies',
                                 'political left', 'On Ayn Rand', 'John David Lewis', 'Letters of Ayn Rand',
                                 'United States', 'reason', 'Atlas Shrugged', 'Routledge Encyclopedia of Philosophy',
                                 'Category:Metaphysicians', 'John P. Mackey', 'Stanford Encyclopedia of Philosophy',
                                 'Broadway theater', 'Category:Women science fiction and fantasy writers',
                                 'Fyodor Dostoevsky', 'Crimean Peninsula', 'Hal Wallis', 'Yale', 'You Came Along',
                                 'File:Ayn Rand Marker.jpg', 'Hollywood, California', 'Neil Peart', 'The Atlas Society',
                                 'Russian Jew', 'Return of the Primitive: The Anti-Industrial Revolution',
                                 'Robert Nozick', 'The Personalist', 'Song of Russia', 'Soviet Union',
                                 'Indigenous peoples of the Americas', 'Tsar', 'Edwin A. Locke', 'Russian Civil War',
                                 'dystopian', 'Russian Empire', 'science fiction', 'Paramount Pictures',
                                 'The Voice of Reason', 'Ludwig von Mises', 'Chicago', 'laissez-faire',
                                 'Category:American atheists', 'Saint Petersburg', 'initiation of force',
                                 'Category:Political philosophers', 'metaphysics', 'Federal Reserve Chairman',
                                 'University of Texas at Austin', 'Category:Critics of religions',
                                 'Category:Prometheus Award winners', 'Second Red Scare', 'rational egoism',
                                 'Category:Jewish American dramatists and playwrights', 'John A. Allison IV',
                                 'October Revolution', 'late-2000s financial crisis', 'The Romantic Manifesto',
                                 'Night of January 16th', 'File:Pola Negri by Ayn Rand cover.jpg',
                                 'philosophical realism', 'Ayn Rand: The Russian Radical', 'Aquinas', 'Nazism',
                                 'We the Living', 'meta-ethical', 'Capitalism: The Unknown Ideal',
                                 'Category:Imperial Russian emigrants to the United States', 'Edmond Rostand',
                                 'Steve Ditko', 'Rational egoism', 'United States presidential election, 1964',
                                 'knowledge', 'Agence France-Presse', 'right-wing politics', 'free markets',
                                 'February Revolution', 'The King of Kings (1927 film)',
                                 'The Chronicle of Higher Education', 'romantic realism', 'Immanuel Kant', 'C-SPAN',
                                 'statism', 'John Locke', 'Nathaniel Branden Institute', 'pro-choice',
                                 'political philosophy', 'Chronicle of Higher Education', 'Isabel Paterson',
                                 'Alex Chadwick', 'Japan Times', 'Red Pawn', 'Category:Pseudonymous writers',
                                 'Love Letters (1945 film)', 'Vladimir Nabokov', 'Category:Atheism activists',
                                 'Benzedrine', 'pseudo-philosophy', 'theocracy', 'Category:Russian novelists',
                                 'Library of Congress', 'New York City', 'Esquire (magazine)', 'Harvard', 'Technicum',
                                 'Vietnam War', 'Bible', 'Category:American anti-fascists', 'Cato Institute',
                                 'Warner Bros.', 'Sidney Hook', 'Category:Atheist philosophers', 'David Hume',
                                 'Journal of Ayn Rand Studies', 'Medicare (United States)', 'Gore Vidal',
                                 'extra (drama)', "Reader's Digest", 'Rush (band)', 'The Objectivist',
                                 'Introduction to Objectivist Epistemology', 'homosexuality', 'pundits',
                                 'Category:Russian women philosophers', 'The Herald (Glasgow)', 'The Guardian',
                                 'epistemology', 'Visa (document)', 'Columbia University', 'history of philosophy',
                                 'Aristotelianism', 'Terry Goodkind', 'Ideal (novel)', 'Category:Imperial Russian Jews',
                                 'Ben-Hur: A Tale of the Christ', 'Category:Ayn Rand', 'Princeton University',
                                 'Nick Gillespie', 'Petrograd State University', 'A priori and a posteriori',
                                 'aesthetics', 'Ed Snider', 'Cecil B. DeMille',
                                 'Category:20th-century American novelists', 'Libertarian Party (United States)',
                                 'Israel', 'The Passion of Ayn Rand (film)',
                                 'University of North Carolina at Chapel Hill', 'ethical egoism',
                                 'Category:American screenwriters', 'military draft', 'Academy Award',
                                 'Cambridge University Press', 'Alan Greenspan', 'Barbara Branden', 'Duke University',
                                 'bourgeois', 'Jim Powell (historian)', 'The Freeman', 'White Army', 'Frederic Bastiat',
                                 'The New York Times', 'newsreels', 'Whittaker Chambers', 'Wendell Willkie',
                                 'Category:Writers from New York City', 'European colonization of the Americas',
                                 'Victor Hugo', 'collectivism', 'E. P. Dutton', 'Academy Award for Documentary Feature',
                                 'L. Neil Smith', 'The God of the Machine', 'Friedrich Schiller', 'Mark Cuban',
                                 'Russian American', 'Social Security (United States)', 'Howard Roark',
                                 'Krause Publications', 'The Fountainhead', 'Ayn Rand and the World She Made',
                                 'classical liberals', 'Erika Holzer', 'David Kelley', 'New American Library',
                                 'Walt Disney World Resort', 'subjectivism', 'Aristotle',
                                 'The Literary Encyclopedia (English)', 'The Nation',
                                 'American Writers: A Journey Through History', 'novelist',
                                 'Category:Jewish philosophers', 'is\xe2\x80\x93ought problem', 'Journals of Ayn Rand',
                                 'mystery (fiction)', 'New York City, New York', 'Conservatism in the United States',
                                 'dystopia', 'Objectivist periodicals', 'The Virtue of Selfishness',
                                 'Category:1905 births', 'bestseller', 'Category:American ethicists',
                                 'American libertarianism', 'communism', 'absolute monarchy', 'Private property',
                                 'libertarians', 'Republican Party (United States)', 'Mimi Reisel Gladstein',
                                 'Category:Critics of feminism', 'Razor (philosophy)', 'totalitarian',
                                 'Category:Philosophers of mind', 'utopian', 'Lingua Franca (magazine)',
                                 'Ayn Rand: A Sense of Life', 'Philosophy: Who Needs It', 'peer-reviewed journal',
                                 'Category:Burials at Kensico Cemetery',
                                 'Goddess of the Market: Ayn Rand and the American Right', 'Clemson University',
                                 'Wikipedia:Persondata', 'BB&amp;T Corporation', 'Brian Doherty (journalist)',
                                 'Religion in the Soviet Union', 'is-ought problem', 'New York Times', 'Mike Wallace',
                                 'Manhattan', 'Charles Murray (political scientist)', 'M. Stanton Evans',
                                 'Lewis &amp; Clark College',
                                 'Motion Picture Alliance for the Preservation of American Ideals',
                                 'File:Spb 06-2012 University Embankment 06.jpg', 'RKO', 'Douglas B. Rasmussen',
                                 'United States nationality law', 'Category:Russian science fiction writers',
                                 'The Passion of Ayn Rand', "Flannery O'Connor", 'H. L. Mencken', 'Prometheus Award',
                                 'amphetamine', 'Finnish language', 'atheist',
                                 'analytic\xe2\x80\x93synthetic dichotomy', 'The Best Years of Our Lives',
                                 'Anthem (novella)', 'lung cancer']

              }]
